// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFudna7jWuShaOsTbMN2355gYCReLEbIM',
    appId: '1:336243629832:web:e2af8e99abecf1872c56bd',
    messagingSenderId: '336243629832',
    projectId: 'diplom-b929a',
    authDomain: 'diplom-b929a.firebaseapp.com',
    storageBucket: 'diplom-b929a.firebasestorage.app',
    measurementId: 'G-7FXESHMSCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpI5GjJmSRe-qKvGjrSYQIGA37yY77Qs',
    appId: '1:336243629832:android:bbea54aac3443e482c56bd',
    messagingSenderId: '336243629832',
    projectId: 'diplom-b929a',
    storageBucket: 'diplom-b929a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB1yYtmyxrMsqhPeRI8K8cqkBQQXKE5Ks',
    appId: '1:336243629832:ios:761d55fd839ea5282c56bd',
    messagingSenderId: '336243629832',
    projectId: 'diplom-b929a',
    storageBucket: 'diplom-b929a.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB1yYtmyxrMsqhPeRI8K8cqkBQQXKE5Ks',
    appId: '1:336243629832:ios:761d55fd839ea5282c56bd',
    messagingSenderId: '336243629832',
    projectId: 'diplom-b929a',
    storageBucket: 'diplom-b929a.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFudna7jWuShaOsTbMN2355gYCReLEbIM',
    appId: '1:336243629832:web:50eedbc73a6bed4a2c56bd',
    messagingSenderId: '336243629832',
    projectId: 'diplom-b929a',
    authDomain: 'diplom-b929a.firebaseapp.com',
    storageBucket: 'diplom-b929a.firebasestorage.app',
    measurementId: 'G-PTMSKJ1SH8',
  );
}
