import 'package:flutter/material.dart';

class Loc {
  static final ValueNotifier<String> lang = ValueNotifier('kz');

  static final Map<String, Map<String, String>> _strings = {
    'kz': {
      'home': 'Басты бет',
      'search': 'Іздеу',
      'favorites': 'Ұнайды',
      'cart': 'Себет',
      'profile': 'Парақша',
      'welcome_title': 'Қош келдіңіз!',
      'welcome_subtitle': 'Бүгін не іздейміз?',
      'popular_categories': 'Танымал санаттар',
      'for_you': 'Сізге арналған',
      'all_categories': 'Барлық санаттар',
      'breakfast': 'Таң ертеңгілік',
      'lunch': 'Түскі ас',
      'dinner': 'Кешкі ас',
      'desserts': 'Тәттілер',
      'snacks': 'Тағамдар',
      'appetizer': 'Алғашқы тағам',
      'side_dish': 'Гарнир',
      'beverage': 'Сусындар',
      'other': 'Басқа',
      'login': 'Кіру',
      'register': 'Тіркелу',
      'checkout_button': 'Рәсімдеу',
      'payment_method': 'Төлем түрі',
      'cash': 'Қолма-қол',
      'card': 'Банк картасымен',
      'address': 'Мекен-жай',
      'edit_address': 'Мекен-жайды өзгерту',
      'save': 'Сақтау',
      'cancel': 'Болдырмау',
      'seller_profile': 'Сатушы профилі',
      'rating': 'Рейтинг',
      'contacts': 'Байланыс',
      'recipes': 'Рецепттер',
      'not_found': 'Тауарлар табылмады',
      'empty': 'Бос',
      'guest': 'Сіз кірмегенсіз (Қонақ)',
      'guest_desc': 'Деректерді көру үшін кіріңіз немесе тіркеліңіз.',
      'add_product': 'Тауар қосу',
      'logout': 'Шығу',
      'contact_info': 'Байланыс ақпараты',
      'email': 'Электрондық пошта',
      'phone': 'Телефон нөмірі',
      'delivery_addr': 'Жеткізу мекенжайы',
      'not_specified': 'Көрсетілмеген',
      'saved': 'Сақталды!',
      'error': 'Қате',
      'must_login': 'Бұл әрекет үшін кіріңіз.',
      'loading': 'Жүктелуде...',
      'app_title': 'Рецепттер әлемі',
      'card_number': 'Карта нөмірі',
      'expiry': 'Ай/Жыл',
      'cvv': 'CVV',
      'success_payment': 'Төлем сәтті өтті!',
      'cash_payment_msg': 'Қолма-қол төлем таңдалды!',
      'retry': 'Қайта көру',
      'description_label': 'Тағам сипаттамасы',
      'ingredients_label': 'Құрамы',
      'steps_label': 'Дайындалуы',
      'details_label': 'Мәліметтер',
      'seller_label': 'Сатушы',
      'condition_label': 'Күйі',
      'location_label': 'Қала',
      'add_to_cart': 'Себетке қосу',
      'contact_seller': 'Сатушымен байланысу',
      'added_to_cart': 'Себетке қосылды!',
      'adding_to_cart': 'Себетке қосылуда...',
      'login_to_add': 'Себетке қосу үшін алдымен кіріңіз.',
      'login_title': 'Жеке аккаунтыңызға кіріңіз',
      'email_label': 'Электрондық пошта',
      'password_label': 'Құпия сөз',
      'forgot_password': 'Құпия сөзді ұмыттыңыз ба?',
      'no_account': 'Аккаунтыңыз жоқ па?',
      'already_have_account': 'Аккаунтыңыз бұрыннан бар ма?',
      'name_label': 'Аты',
      'surname_label': 'Тегі',
      'phone_label': 'Телефон нөмірі',
      'repeat_password_label': 'Құпия сөзді қайталау',
      'instagram_label': 'Instagram',
      'seller_info': 'Сатушы мәліметтері',
      'login_as_guest': 'Қонақ ретінде кіру',
      'register_title': 'Жаңа аккаунт',
      'register_subtitle': 'Тіркеліп, рецепттерді таңдаулыға сақтаңыз',
      'item_removed': 'Тауар жойылды',
      'total': 'Барлығы',
      'favorites_empty': 'Таңдаулыңыз бос',
      'cart_empty': 'Себет бос',
    },
    'ru': {
      'home': 'Главная',
      'search': 'Поиск',
      'favorites': 'Избранное',
      'cart': 'Корзина',
      'profile': 'Профиль',
      'welcome_title': 'Добро пожаловать!',
      'welcome_subtitle': 'Что ищем сегодня?',
      'popular_categories': 'Популярные категории',
      'for_you': 'Для вас',
      'all_categories': 'Все категории',
      'breakfast': 'Завтрак',
      'lunch': 'Обед',
      'dinner': 'Ужин',
      'desserts': 'Десерты',
      'snacks': 'Закуски',
      'appetizer': 'Первые блюда',
      'side_dish': 'Гарнир',
      'beverage': 'Напитки',
      'other': 'Другое',
      'login': 'Войти',
      'register': 'Регистрация',
      'checkout_button': 'Оформить заказ',
      'payment_method': 'Оплата',
      'cash': 'Наличными',
      'card': 'Картой',
      'address': 'Адрес',
      'edit_address': 'Изменить адрес',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'seller_profile': 'Профиль продавца',
      'rating': 'Рейтинг',
      'contacts': 'Контакты',
      'recipes': 'Рецепты',
      'not_found': 'Товары не найдены',
      'empty': 'Пусто',
      'guest': 'Вы гость',
      'guest_desc': 'Войдите для просмотра данных.',
      'add_product': 'Добавить товар',
      'logout': 'Выйти',
      'contact_info': 'Контактная информация',
      'email': 'Электронная почта',
      'phone': 'Номер телефона',
      'delivery_addr': 'Адрес доставки',
      'not_specified': 'Не указано',
      'saved': 'Сохранено!',
      'error': 'Ошибка',
      'must_login': 'Пожалуйста, ввойдите в систему.',
      'loading': 'Загрузка...',
      'app_title': 'Мир рецептов',
      'card_number': 'Номер карты',
      'expiry': 'ММ/ГГ',
      'cvv': 'CVV',
      'success_payment': 'Оплата прошла успешно!',
      'cash_payment_msg': 'Выбрана оплата наличными!',
      'retry': 'Повторить',
      'description_label': 'Описание блюда',
      'ingredients_label': 'Состав',
      'steps_label': 'Приготовление',
      'details_label': 'Детали',
      'seller_label': 'Продавец',
      'condition_label': 'Состояние',
      'location_label': 'Город',
      'login_to_add': 'Войдите, чтобы добавить в корзину.',
      'login_title': 'Войдите в личный аккаунт',
      'email_label': 'Электронная почта',
      'password_label': 'Пароль',
      'forgot_password': 'Забыли пароль?',
      'no_account': 'Нет аккаунта?',
      'already_have_account': 'Уже есть аккаунт?',
      'name_label': 'Имя',
      'surname_label': 'Фамилия',
      'phone_label': 'Номер телефона',
      'repeat_password_label': 'Повторите пароль',
      'instagram_label': 'Instagram',
      'seller_info': 'Данные продавца',
      'login_as_guest': 'Войти как гость',
      'register_title': 'Новый аккаунт',
      'register_subtitle': 'Зарегистрируйтесь, чтобы сохранять рецепты',
      'add_to_cart': 'В корзину',
      'contact_seller': 'Связаться с продавцом',
      'added_to_cart': 'Добавлено в корзину!',
      'adding_to_cart': 'Добавление...',
      'item_removed': 'Товар удален',
      'total': 'Итого',
      'favorites_empty': 'Избранное пусто',
      'cart_empty': 'Корзина пуста',
    },
    'en': {
      'home': 'Home',
      'search': 'Search',
      'favorites': 'Favorites',
      'cart': 'Cart',
      'profile': 'Profile',
      'welcome_title': 'Welcome!',
      'welcome_subtitle': 'What are we looking for?',
      'popular_categories': 'Popular Categories',
      'for_you': 'For You',
      'all_categories': 'All Categories',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'desserts': 'Desserts',
      'snacks': 'Snacks',
      'appetizer': 'Appetizers',
      'side_dish': 'Side Dish',
      'beverage': 'Beverages',
      'other': 'Other',
      'login': 'Login',
      'register': 'Register',
      'checkout_button': 'Checkout',
      'payment_method': 'Payment',
      'cash': 'Cash',
      'card': 'Card',
      'address': 'Address',
      'edit_address': 'Edit Address',
      'save': 'Save',
      'cancel': 'Cancel',
      'seller_profile': 'Seller Profile',
      'rating': 'Rating',
      'contacts': 'Contacts',
      'recipes': 'Recipes',
      'not_found': 'Items not found',
      'empty': 'Empty',
      'guest': 'You are a Guest',
      'guest_desc': 'Login or register to view data.',
      'add_product': 'Add Product',
      'logout': 'Logout',
      'contact_info': 'Contact Info',
      'email': 'Email',
      'phone': 'Phone',
      'delivery_addr': 'Delivery Address',
      'not_specified': 'Not specified',
      'saved': 'Saved!',
      'error': 'Error',
      'must_login': 'Please login to continue.',
      'loading': 'Loading...',
      'app_title': 'Recipe World',
      'card_number': 'Card Number',
      'expiry': 'MM/YY',
      'cvv': 'CVV',
      'success_payment': 'Payment Successful!',
      'cash_payment_msg': 'Cash payment selected!',
      'retry': 'Retry',
      'description_label': 'Description',
      'ingredients_label': 'Ingredients',
      'steps_label': 'Preparation Steps',
      'details_label': 'Details',
      'seller_label': 'Seller',
      'condition_label': 'Condition',
      'location_label': 'Location',
      'add_to_cart': 'Add to Cart',
      'contact_seller': 'Contact Seller',
      'added_to_cart': 'Added to cart!',
      'adding_to_cart': 'Adding...',
      'login_to_add': 'Please login to add to cart.',
      'login_title': 'Log in to your account',
      'email_label': 'Email address',
      'password_label': 'Password',
      'forgot_password': 'Forgot password?',
      'no_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'name_label': 'Name',
      'surname_label': 'Surname',
      'phone_label': 'Phone number',
      'repeat_password_label': 'Repeat password',
      'instagram_label': 'Instagram',
      'seller_info': 'Seller details',
      'login_as_guest': 'Login as guest',
      'register_title': 'New Account',
      'register_subtitle': 'Sign up to save your favorite recipes',
      'item_removed': 'Item removed',
      'total': 'Total',
      'favorites_empty': 'Favorites is empty',
      'cart_empty': 'Cart is empty',
    },
  };

  static String tr(String key) {
    return _strings[lang.value]?[key] ?? _strings['kz']?[key] ?? key;
  }
}
